### ISSUE TITLE
The exception occurred on the server. Find out why

### ISSUE THREAD

**Issue by Brownshome** [Brownshome/script-wars#17]
<pre>Exception in thread "Unnamed Game thread" java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
        at brownshome.scriptwars.game.GridDisplayHandler.print(GridDisplayHandler.java:39)
        at brownshome.scriptwars.game.tanks.TankGame.displayGame(TankGame.java:189)
        at brownshome.scriptwars.game.tanks.TankGame.displayGame(TankGame.java:33)
        at brownshome.scriptwars.game.Game.gameLoop(Game.java:253)
        at java.lang.Thread.run(Thread.java:745)
</pre>

This occurred in synchronized blocks. Maybe the send function caused the code to block, releasing the locks?

**Comment by Brownshome** [comment]
I'll re-open this if the issue re-surfaces
